### ISSUE TITLE
Thoughts on using a pipe-able api like rxjs 6 for better code splitting support

### ISSUE THREAD

**Issue by Place1** [jinhduong/linq-fns#5]
Hi, love the library, just wanted to throw the idea up for using a pipe friendly api to help with codesplitting

**Comment by jinhduong** [comment]
You're right, the thing we're talking about is `tree-shaking`. But as you know the original design of this library is OOP, so it will take several time to re-write it for `tree-shaking`. 
So I will think of it when the next updates.
